# Generated by Django 3.1 on 2023-01-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.SmallIntegerField(choices=[(1, 'Створення'), (2, 'Зміна'), (3, 'Видалення'), (4, 'Багато до багатьох (зміна)'), (5, 'Багато до багатьох (зміна)(Reverse)'), (6, 'Багато до багатьох (додавання)'), (7, 'Багато до багатьох (додавання)(Reverse)'), (8, 'Багато до багатьох (видалення)'), (9, 'Багато до багатьох (видалення)(Reverse)'), (10, 'Спроба видалення')], db_index=True, verbose_name='Event type')),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='Object ID')),
                ('object_repr', models.TextField(blank=True, null=True, verbose_name='Object representation')),
                ('object_json_repr', models.TextField(blank=True, null=True, verbose_name='Object JSON representation')),
                ('changed_fields', models.JSONField(blank=True, null=True, verbose_name='Changed fields')),
                ('user_data', models.JSONField(editable=False, null=True)),
                ('hr_object_repr', models.JSONField(editable=False, null=True)),
                ('user_pk_as_string', models.CharField(blank=True, help_text='String version of the user pk', max_length=255, null=True, verbose_name='User PK as string')),
                ('user_as_string', models.CharField(blank=True, help_text='String version of the user', max_length=255, null=True, verbose_name='User as string')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date time')),
                ('change_comment', models.CharField(max_length=250, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'CRUD event',
                'verbose_name_plural': 'CRUD events',
                'ordering': ['-datetime'],
                'default_permissions': ('delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_type', models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Failed login')], verbose_name='Event type')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date time')),
                ('user_as_string', models.CharField(blank=True, help_text='String version of the user', max_length=255, null=True, verbose_name='User as string')),
            ],
            options={
                'verbose_name': 'login event',
                'verbose_name_plural': 'login events',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=254, verbose_name='URL')),
                ('method', models.CharField(db_index=True, max_length=20, verbose_name='Method')),
                ('query_string', models.TextField(null=True, verbose_name='Query string')),
                ('remote_ip', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Remote IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date time')),
            ],
            options={
                'verbose_name': 'request event',
                'verbose_name_plural': 'request events',
                'ordering': ['-datetime'],
                'default_permissions': ('delete', 'view'),
            },
        ),
    ]
