# Generated by Django 4.1.7 on 2023-03-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_authorisedperson_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreorganization',
            options={'permissions': [('add_simple_organization', 'Може створити локальну організацію'), ('change_simple_organization', 'Може змінити локальну організацію'), ('delete_simple_organization', 'Може видалити локальну організацію'), ('add_local_user', 'Може створити локального користувача'), ('change_local_user', 'Може змінити локального користувача'), ('delete_local_user', 'Може видалити локального користувача'), ('change_org_profile', 'Може змінювати профіль організації'), ('change_local_user_password', 'Може змінювати пароль  локального користувача')], 'verbose_name': 'Центр комплектування та соціальної підтримки', 'verbose_name_plural': 'Центри комплектування та соціальної підтримки'},
        ),
    ]
