# Generated by Django 4.1.7 on 2023-03-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coreorganization_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupOrganization',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='av_color',
        ),
        migrations.RemoveField(
            model_name='department',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='coreorganization',
            unique_together={('edrpou',)},
        ),
        migrations.RemoveField(
            model_name='coreorganization',
            name='org_type',
        ),
        migrations.RemoveField(
            model_name='coreorganization',
            name='organization',
        ),
    ]
