# Generated by Django 4.1.7 on 2023-02-26 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='child',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='child',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='education',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='language',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militarymovement',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='militarymovement',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='militarymovement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='place_of_birth',
            field=models.CharField(max_length=100, verbose_name='Місце народження'),
        ),
        migrations.AlterField(
            model_name='militaryrank',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militaryregistrationviolation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='militaryspecialty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mobilizationpostponement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
