# Generated by Django 4.1.7 on 2023-02-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0002_alter_bloodtype_id_alter_child_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='militarymovement',
            options={'verbose_name': 'Дані про перетин кордону', 'verbose_name_plural': 'Дані про перетин кордону'},
        ),
        migrations.AlterModelOptions(
            name='mobilizationpostponement',
            options={'verbose_name': 'Відстрочка від мобілізації', 'verbose_name_plural': 'Відстрочки від мобілізації'},
        ),
        migrations.AlterField(
            model_name='militarymovement',
            name='departure_date',
            field=models.DateField(verbose_name='дата виїзду'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='accounting_group',
            field=models.CharField(blank=True, choices=[('AD', 'Військовослужбовець строкової служби'), ('CS', 'Військовослужбовець контрактної служби'), ('R', "Військовозобов'язаний запасу"), ('NG', 'Військовослужбовець Національної гвардії'), ('TD', 'Військовослужбовець територіальної оборони'), ('O', 'Інше')], max_length=10, null=True, verbose_name='Група обліку'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='family_status',
            field=models.CharField(choices=[('S', 'Неодружений/неодружена'), ('M', 'Одружений/одружена'), ('D', 'Розлучений/розлучена'), ('W', 'Вдівець/вдова')], default='S', max_length=100, verbose_name='Сімейний стан'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='health_status',
            field=models.CharField(choices=[('A1', 'Здатний до призову'), ('A2', 'Обмежено здатний до призову'), ('B', 'Тимчасово нездатний до призову'), ('C', 'Постійно нездатний до призову')], default='A1', max_length=100, verbose_name='Ступінь придатності до військової служби за станом здоров’я'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='military_education_level',
            field=models.CharField(choices=[('SE', 'Середня загальна освіта'), ('VO', 'Професійно-технічна освіта'), ('HI', 'Вища освіта'), ('PG', 'Післядипломна освіта'), ('NO', 'Відсутня')], default='NO', max_length=10, null=True, verbose_name='Рівень військової освіти'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='military_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryrank', verbose_name='Військове звання'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='military_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryspecialty', verbose_name='Військово-облікова спеціальність'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='reserve_category',
            field=models.CharField(blank=True, choices=[('A', 'Категорія А'), ('B', 'Категорія Б'), ('C', 'Категорія В')], max_length=1, null=True, verbose_name='Категорія запасу'),
        ),
    ]
