# Generated by Django 4.1.7 on 2023-03-02 07:32

import apps.core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_authorisedperson_author_and_more'),
        ('mrs', '0003_alter_militarymovement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?')),
                ('unique_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення')),
                ('date_edit', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни')),
                ('author_display_name', models.TextField(editable=False, null=True, verbose_name='**Автор')),
                ('editor_display_name', models.TextField(editable=False, null=True, verbose_name='**Останій редактор(відображення)')),
                ('name', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='Назва')),
                ('full_name', models.CharField(db_index=True, max_length=256, verbose_name='Повна назва')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='Адреса')),
                ('edrpou', models.CharField(db_index=True, max_length=10, verbose_name='ЄДРПОУ')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='EMAIL')),
                ('main_unit', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уповноважена особа')),
                ('main_unit_state', models.CharField(blank=True, max_length=200, null=True, verbose_name='Посада уповноваженої особи')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примітка')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор')),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор')),
                ('organization', models.ForeignKey(editable=False, help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.coreorganization', verbose_name='**Організація')),
            ],
            options={
                'verbose_name': 'Роботодавець',
                'verbose_name_plural': 'Роботодавці',
            },
            bases=(apps.core.mixins.CheckProtected, apps.core.mixins.RelatedObjects, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?')),
                ('unique_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення')),
                ('date_edit', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни')),
                ('author_display_name', models.TextField(editable=False, null=True, verbose_name='**Автор')),
                ('editor_display_name', models.TextField(editable=False, null=True, verbose_name='**Останій редактор(відображення)')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('hired_date', models.DateField(verbose_name='Прийнятий')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Звільнений')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrs.company')),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор')),
            ],
            options={
                'verbose_name': 'Місце роботи',
                'verbose_name_plural': 'Місця роботи',
            },
            bases=(apps.core.mixins.CheckProtected, apps.core.mixins.RelatedObjects, models.Model),
        ),
        migrations.AlterModelOptions(
            name='militaryperson',
            options={'verbose_name': 'Віськовозобов`язаний', 'verbose_name_plural': 'Віськовозобов`язані особи'},
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A-', max_length=3, verbose_name='Група крові та резус фактор'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/military_photos/'),
        ),
        migrations.DeleteModel(
            name='BloodType',
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='military_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrs.militaryperson'),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='organization',
            field=models.ForeignKey(editable=False, help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.coreorganization', verbose_name='**Організація'),
        ),
    ]
