# Generated by Django 4.1.7 on 2023-03-02 08:58

import apps.core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coreorganization_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrs', '0004_company_companyemployee_alter_militaryperson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Дитина', 'verbose_name_plural': 'Діти'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Навчання у ВУЗі', 'verbose_name_plural': 'Навчання у ВУЗах'},
        ),
        migrations.AlterModelOptions(
            name='foreignlanguage',
            options={'verbose_name': 'Знання іноземних мов', 'verbose_name_plural': 'Знання іноземних мов'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Іноземна мова', 'verbose_name_plural': 'Іноземні мови'},
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='child',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrs.company', verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='military_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryperson'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(max_length=255, verbose_name='Напрямок'),
        ),
        migrations.AlterField(
            model_name='education',
            name='specialty',
            field=models.CharField(max_length=255, verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrs.language', verbose_name='Мова'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='language_level',
            field=models.CharField(choices=[('A1', 'Elementary'), ('A2', 'Pre-Intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficient')], max_length=2, verbose_name='Рівень володіння'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='passport_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Закінчення дії'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='passport_issue_date',
            field=models.DateField(verbose_name='Дата видачі'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='passport_issuing_authority',
            field=models.CharField(max_length=255, verbose_name='Виданий'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='passport_number',
            field=models.CharField(max_length=6, verbose_name='Номер паспорту'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='passport_series',
            field=models.CharField(max_length=2, verbose_name='Серія паспорт'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/military_photos/', verbose_name='ФОТО'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='taxpayer_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='РНОКПП'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?')),
                ('unique_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення')),
                ('date_edit', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни')),
                ('author_display_name', models.TextField(editable=False, null=True, verbose_name='**Автор')),
                ('editor_display_name', models.TextField(editable=False, null=True, verbose_name='**Останій редактор(відображення)')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор')),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор')),
                ('military_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryperson')),
                ('organization', models.ForeignKey(editable=False, help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.coreorganization', verbose_name='**Організація')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.mixins.CheckProtected, apps.core.mixins.RelatedObjects, models.Model),
        ),
        migrations.CreateModel(
            name='MilitaryPersonPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?')),
                ('unique_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення')),
                ('date_edit', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни')),
                ('author_display_name', models.TextField(editable=False, null=True, verbose_name='**Автор')),
                ('editor_display_name', models.TextField(editable=False, null=True, verbose_name='**Останій редактор(відображення)')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор')),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор')),
                ('military_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrs.militaryperson')),
                ('organization', models.ForeignKey(editable=False, help_text='До якої організації відноситься інформація', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.coreorganization', verbose_name='**Організація')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Контактні телефони',
            },
            bases=(apps.core.mixins.CheckProtected, apps.core.mixins.RelatedObjects, models.Model),
        ),
    ]
