# Generated by Django 4.1.7 on 2023-03-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0005_alter_child_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Повістка', 'verbose_name_plural': 'Повістки'},
        ),
        migrations.AddField(
            model_name='notice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrs.company'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_file',
            field=models.FileField(default=1, upload_to='uploads/notice/', verbose_name='Файл повістки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('A1', 'Повістка для уточнення облікових даних'), ('A2', 'Повістка для проходження медкомісії'), ('A3', 'Повістка-призов до ЗСУ'), ('A4', 'Мобілізаційне розпорядження')], default='A1', max_length=2, verbose_name='Тип повістки'),
        ),
        migrations.CreateModel(
            name='NoticeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='Дата відправки')),
                ('place_type', models.CharField(choices=[('H', 'Відправлена за місцем проживання'), ('W', 'Відправлена за місцем роботи')], default='H', max_length=1, verbose_name='Куди направлено')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('delivery_type', models.CharField(choices=[('POST', 'Поштою'), ('PERSONAL', 'Наручно'), ('VIBER', 'VIBER'), ('MAIL', 'MAIL')], max_length=10, verbose_name='Спосіб доставки')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrs.notice')),
            ],
            options={
                'verbose_name': 'Доставка повістки',
                'verbose_name_plural': 'Доставка повістки',
            },
        ),
    ]
