# Generated by Django 4.1.7 on 2023-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0006_alter_notice_options_notice_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticedelivery',
            name='send_on_save',
            field=models.BooleanField(default=True, verbose_name='Відправити автоматично при збереженні'),
        ),
    ]
