# Generated by Django 4.1.7 on 2023-03-02 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrs', '0007_noticedelivery_send_on_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizationpostponement',
            name='detail_file',
            field=models.FileField(upload_to='', verbose_name='Копія документа що підтверджеє відстрочку'),
        ),
        migrations.CreateModel(
            name='MobilizationPostponementDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення')),
                ('date_edit', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни')),
                ('author_display_name', models.TextField(editable=False, null=True, verbose_name='**Автор')),
                ('editor_display_name', models.TextField(editable=False, null=True, verbose_name='**Останій редактор(відображення)')),
                ('reason', models.CharField(choices=[('ST', 'навчання'), ('WO', 'робота'), ('FA', 'сімейні обставини'), ('HE', "стан здоров'я"), ('OT', 'інша підстава')], max_length=2, verbose_name='Підстава відстрочки')),
                ('details', models.TextField(blank=True, verbose_name='Деталізація підстави')),
                ('detail_file', models.FileField(upload_to='', verbose_name='Копія документа що підтверджеє відстрочку')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Початок дії')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Кінець дії')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор')),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор')),
                ('military_person', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryperson')),
            ],
            options={
                'verbose_name': 'Документ про відстрочку',
                'verbose_name_plural': 'Документи про відстрочку',
            },
        ),
    ]
