# Generated by Django 4.1.7 on 2023-03-02 15:15

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0012_militaryperson_search_vector'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='militaryperson',
            index=django.contrib.postgres.indexes.GinIndex(fields=['taxpayer_id'], name='taxpayer_id_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='militaryperson',
            index=django.contrib.postgres.indexes.GinIndex(fields=['passport_number'], name='passport_number_gin_index', opclasses=['gin_trgm_ops']),
        ),
    ]
