# Generated by Django 4.1.7 on 2023-03-02 15:22

import apps.mrs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0013_militaryperson_taxpayer_id_gin_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='militaryperson',
            index=apps.mrs.models.UpperIndex(fields=['taxpayer_id'], name='taxpayer_id_upper_index'),
        ),
        migrations.AddIndex(
            model_name='militaryperson',
            index=apps.mrs.models.UpperGinIndex(fields=['taxpayer_id'], name='taxpayer_id_gin_upper_index', opclasses=['gin_trgm_ops']),
        ),
    ]
