# Generated by Django 4.1.7 on 2023-03-02 15:35

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0014_militaryperson_taxpayer_id_upper_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='militaryperson',
            index=django.contrib.postgres.indexes.HashIndex(fields=['taxpayer_id'], name='taxpayer_id_hash_index'),
        ),
    ]
