# Generated by Django 4.1.7 on 2023-03-03 11:10

import apps.mrs.models
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0015_militaryperson_taxpayer_id_hash_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizationpostponementdoc',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новий'), ('SACCESS', 'Прийнято'), ('DENIED', 'Відмовлено')], default='NEW', max_length=10, verbose_name='Статус документа'),
        ),
        migrations.AddField(
            model_name='mobilizationpostponementorgdoc',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новий'), ('SACCESS', 'Прийнято'), ('DENIED', 'Відмовлено')], default='NEW', max_length=10, verbose_name='Статус документа'),
        ),
        migrations.AddIndex(
            model_name='militaryperson',
            index=apps.mrs.models.UpperIndex(fields=['passport_number'], name='passport_number_upper_index'),
        ),
        migrations.AddIndex(
            model_name='militaryperson',
            index=apps.mrs.models.UpperGinIndex(fields=['passport_number'], name='pass_n_gin_upper_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='militaryperson',
            index=django.contrib.postgres.indexes.HashIndex(fields=['passport_number'], name='passport_number_hash_index'),
        ),
    ]
