# Generated by Django 4.1.7 on 2023-03-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0016_mobilizationpostponementdoc_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilizationpostponementdoc',
            options={'permissions': [('can_review_postponement_doc', 'Може розглядати документ про бронювання')], 'verbose_name': 'Документ про відстрочку (від особи)', 'verbose_name_plural': 'Документи про відстрочку (від особи)'},
        ),
        migrations.AlterModelOptions(
            name='mobilizationpostponementorgdoc',
            options={'permissions': [('can_review_postponement_doc', 'Може розглядати документ про бронювання')], 'verbose_name': 'Документ про відстрочку  (від ЮР особи)', 'verbose_name_plural': 'Документи про відстрочку (від ЮР особи)'},
        ),
        migrations.RemoveField(
            model_name='child',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='company',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='education',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='foreignlanguage',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='language',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='militarymovement',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='militaryperson',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='militarypersonphone',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='organization',
        ),
        migrations.AlterField(
            model_name='mobilizationpostponementdoc',
            name='status',
            field=models.CharField(choices=[('NEW', 'Очікує підтвердження'), ('SACCESS', 'Прийнято'), ('DENIED', 'Відмовлено')], default='NEW', max_length=10, verbose_name='Статус документа'),
        ),
        migrations.AlterField(
            model_name='mobilizationpostponementorgdoc',
            name='status',
            field=models.CharField(choices=[('NEW', 'Очікує підтвердження'), ('SACCESS', 'Прийнято'), ('DENIED', 'Відмовлено')], default='NEW', max_length=10, verbose_name='Статус документа'),
        ),
    ]
