# Generated by Django 4.1.7 on 2023-03-03 14:53

import apps.core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_grouporganization_remove_coreuser_av_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrs', '0017_alter_mobilizationpostponementdoc_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCKEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?')),
                ('unique_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення')),
                ('date_edit', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни')),
                ('author_display_name', models.TextField(editable=False, null=True, verbose_name='**Автор')),
                ('editor_display_name', models.TextField(editable=False, null=True, verbose_name='**Останій редактор(відображення)')),
                ('hired_date', models.DateField(verbose_name='Прийнятий на облік')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Знятий з обліку')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор')),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор')),
                ('military_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryperson')),
                ('tck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coreorganization', verbose_name='ТЦК')),
            ],
            options={
                'verbose_name': 'ТЦК обліку',
                'verbose_name_plural': 'ТЦК обліку',
            },
            bases=(apps.core.mixins.CheckProtected, apps.core.mixins.RelatedObjects, models.Model),
        ),
    ]
