# Generated by Django 4.1.7 on 2023-03-06 12:47

import apps.core.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrs', '0019_alter_militaryspecialty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilizationpostponementorgdoc',
            name='military_person',
            field=models.ForeignKey(help_text='Пошук за РНОКПП або паспортом', on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryperson', verbose_name='Військовозобовязаний'),
        ),
        migrations.AlterField(
            model_name='noticedelivery',
            name='result_file',
            field=models.FileField(blank=True, help_text='** Фотофіксація документа що підтверджує доставку', null=True, upload_to='uploads/notice_result/', verbose_name='Файл підтвердження'),
        ),
        migrations.CreateModel(
            name='MilitaryTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='**Дані помічено на видалення?')),
                ('unique_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Інформацію, відмічену за допомогою UUID, можна використовувати без необхідності вирішення конфлікту імен', verbose_name='**Унікальний ідентифікатор запису, в загальному просторі імен')),
                ('date_add', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='**Дата створення')),
                ('date_edit', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='**Дата останньої зміни')),
                ('author_display_name', models.TextField(editable=False, null=True, verbose_name='**Автор')),
                ('editor_display_name', models.TextField(editable=False, null=True, verbose_name='**Останій редактор(відображення)')),
                ('start_date', models.DateField(verbose_name='Дата відправки')),
                ('days_count', models.PositiveIntegerField(verbose_name='Кількість днів')),
                ('military_base', models.CharField(max_length=255, verbose_name='в/ч чи організація')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примітка')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_author', to=settings.AUTH_USER_MODEL, verbose_name='**Автор')),
                ('editor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_editor', to=settings.AUTH_USER_MODEL, verbose_name='**Останій редактор')),
                ('military_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryperson')),
                ('military_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrs.militaryspecialty', verbose_name='Військово-облікова спеціальність')),
            ],
            options={
                'verbose_name': 'Навчальні збори',
                'verbose_name_plural': 'Навчальні збори',
            },
            bases=(apps.core.mixins.CheckProtected, apps.core.mixins.RelatedObjects, models.Model),
        ),
    ]
