# Generated by Django 4.1.7 on 2023-03-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0020_alter_mobilizationpostponementorgdoc_military_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mrs.company', verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='noticedelivery',
            name='send_on_save',
            field=models.BooleanField(default=False, help_text='** Автоматична відправка буде здійснена якщо обрати месенджер, або електронну пошту', verbose_name='Відправити автоматично при збереженні'),
        ),
    ]
