# Generated by Django 4.1.7 on 2023-03-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0021_alter_notice_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryperson',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], db_index=True, default='A-', max_length=5, verbose_name='Група крові та резус фактор'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='date_of_birth',
            field=models.DateField(db_index=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='disability_group',
            field=models.CharField(choices=[('I', 'I група'), ('II', 'II група'), ('III', 'III група'), ('IV', 'IV група'), ('N', 'немає інвалідності')], db_index=True, default='N', max_length=3, verbose_name='Група інвалідності'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='first_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='health_status',
            field=models.CharField(choices=[('A1', 'Здатний до призову'), ('A2', 'Обмежено здатний до призову'), ('B', 'Тимчасово нездатний до призову'), ('C', 'Постійно нездатний до призову')], db_index=True, default='A1', max_length=100, verbose_name='Ступінь придатності до військової служби за станом здоров’я'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='militaryperson',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='По-батькові'),
        ),
    ]
