# Generated by Django 4.1.7 on 2023-03-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrs', '0022_alter_militaryperson_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizationpostponementdoc',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина відмови'),
        ),
        migrations.AddField(
            model_name='mobilizationpostponementorgdoc',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина відмови'),
        ),
    ]
